### PR TITLE
fix(core): allow only 4 digits for year in date input

### LINKED ISSUE #56: Incorrect date is fetched using keyboard in "Do this" block
**Describe the bug**
Incorrect date is fetched using keyboard in "Do this" block

For further information on the issue refer to the link below:
https://sourcefuse.atlassian.net/browse/OPX-9082

### PR DESCRIPTION
**Pull request by arpit1503khanna**
## Description

1. Allow only 4 digits for year in date input
2. Fix the issue when enter date with keyboard

Fixes #56 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by AryanshSourcefuse — APPROVED** [review]

File: projects/workflows-creator/src/lib/builder/group/group.component.ts [hunk 1]
```diff
@@ -590,11 +590,19 @@ export class GroupComponent<E> implements OnInit, AfterViewInit {
...
+    type: string,
+    event: any,
+  ) {
+    const response = this.getLibraryValue(node, $event, type, {});
+
+    //check whether the entered key is "ENTER" key
+    if (event.keyCode === 13) {
+      callback(response);
+    }
   }
```
Comment (yeshamavani) [inline projects/workflows-creator/src/lib/builder/group/group.component.ts:606]: is this a breaking change ?

Comment (arpit1503khanna) [reply projects/workflows-creator/src/lib/builder/group/group.component.ts:606]: No

**Review by yeshamavani — APPROVED** [review]
