### PR TITLE
fix(core): Values are not retained after saving for 'Else Do this' block

### LINKED ISSUE #71: WF| Values are not retained after saving for 'Else Do this' block when 'Item/Subitem is created' is selected in the workflow
**Describe the bug**
WF| Values are not retained after saving for 'Else Do this' block when 'Item/Subitem is created' is selected in the workflow
for further information please check the following link
https://sourcefuse.atlassian.net/browse/OPX-9649

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by Deepika516**
WF| Values are not retained after saving for 'Else Do this' block when 'Item/Subitem is created' is selected in the workflow
for further information please check the following link
GH-71

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #71 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: projects/workflows-creator/src/lib/builder/builder.component.ts [hunk 1]
```diff
@@ -202,8 +202,31 @@ export class BuilderComponent<E> implements OnInit, OnChanges {
...
       });
       this.updateDiagram();
+      this.hideElseBlockIfRequired();
     }
   }
+  /**
+   * This function checks if the else block should be hidden based on the type and number of events in
+   * the event group.
+   */
+  hideElseBlockIfRequired() {
```
Comment (rohit-sourcefuse) [inline projects/workflows-creator/src/lib/builder/builder.component.ts:212]: Here's an improved version of the hideElseBlockIfRequired for better readability:

```javascript
hideElseBlockIfRequired() {
    const events = this.eventGroups[0].children;
    const firstEvent = events[0]?.node;
    
    if (!firstEvent) {
        this.elseBlockHidden = false;
        return;
    }

    let value = firstEvent.state.get('value');

    if (typeof value === 'object') {
        value = value.value;
    }

    const eventType = firstEvent.getIdentifier();
    const eventValue = firstEvent.state.get('value');
    const eventValueType = firstEvent.state.get('valueType');

    this.elseBlockHidden = eventType === EventTypes.OnIntervalEvent ||
        eventType === EventTypes.OnAddItemEvent ||
        (eventType === EventTypes.OnChangeEvent &&
            (eventValue === ValueTypes.AnyValue ||
                eventValueType === ValueTypes.AnyValue));
}
```
changes :

- We check if firstEvent exists before accessing its properties to avoid errors.
- The code is structured to handle cases where firstEvent might be undefined.
- The logic for determining value, eventType, eventValue, and eventValueType remains the same.

This requires testing before implementation, this code improves the readability

File: projects/workflows-creator/src/lib/builder/builder.component.ts [hunk 2]
```diff
@@ -202,8 +202,31 @@ export class BuilderComponent<E> implements OnInit, OnChanges {
...
+    const events = this.eventGroups[0].children;
+    let value = events[0].node.state.get('value');
```
Comment (yeshamavani) [inline projects/workflows-creator/src/lib/builder/builder.component.ts:214]: there is a possibility that this line will give error 
since the length check is later

**Review by yeshamavani — CHANGES_REQUESTED** [review]

File: projects/workflows-creator/src/lib/builder/builder.component.ts (hunk 1 above)
Comment (Deepika516) [reply projects/workflows-creator/src/lib/builder/builder.component.ts:213]: Done the changes .

File: projects/workflows-creator/src/lib/builder/builder.component.ts (hunk 2 above)
Comment (Deepika516) [reply projects/workflows-creator/src/lib/builder/builder.component.ts]: thr is always a  default node grp in this.eventGroups, it will never be empty , so no error will occur in future

**Review by yeshamavani — APPROVED** [review]
