### PR TITLE
fix(core): reset the date,datetime column when another column is selected

### LINKED ISSUE #74: For columns 'Date' & 'Date/Time' values are retained even when the user has changed the column and select it again
**Describe the bug**
For columns 'Date' & 'Date/Time' values are retained even when the user has changed the column and select it again

For further information on the issue refer to the link below:
https://sourcefuse.atlassian.net/browse/OPX-9647

### PR DESCRIPTION
**Pull request by arpit1503khanna**
## Description
Reset the date,datetime column when another column is selected

Fixes #74 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: projects/workflows-creator/src/lib/builder/group/group.component.ts [hunk 1]
```diff
@@ -614,6 +626,26 @@ export class GroupComponent<E> implements OnInit, AfterViewInit {
...
+    dateTimeField?: string,
+  ) {
+    //if inputType->dateTime
+    switch (inputType) {
+      case InputTypes.DateTime:
+        if (dateTimeField == 'date') {
+          this.dateTime.date = event;
+        } else {
+          this.dateTime.time = event;
+        }
```
Comment (yeshamavani) [inline projects/workflows-creator/src/lib/builder/group/group.component.ts:642]: ternary operator here

**Review by yeshamavani — CHANGES_REQUESTED** [review]

**Review by AryanshSourcefuse — APPROVED** [review]

File: projects/workflows-creator/src/lib/builder/group/group.component.ts (hunk 1 above)
Comment (arpit1503khanna) [reply projects/workflows-creator/src/lib/builder/group/group.component.ts:642]: We are updating different entity in 'if' and in 'else', so I suppose it is better like this only
